### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by dicearr** [dicearr/praw#1]
- [x] Improve backend tests to cover the whole API
- [ ] Improve frontend tests
- [ ] ~Integrate tests using --projects~
- [x] Create the technical documentation
- [x] Update README.md
- [x] Compile Angular in production mode
- [ ] Add searchbox to manually change location
- [x] Move Angular content to Routes and Componentize more
- [x] Refactor Angular services 
- [x] Add HTTPS to Heroku 'to allow chrome getCurrentPosition'
- [ ] Improve the interface
